bias_replacement_dict = {
    "housewife": "homemaker",
    "fireman": "firefighter",
    "policeman": "police officer",
    "policewoman": "police officer",
    "stewardess": "flight attendant",
    "businessman": "businessperson",
    "mankind": "humankind",
    "chairman": "chairperson",
    "actress": "actor",
    "waitress": "waiter",
    "congressman": "congressperson",
    "heroine": "hero",
    "salesman": "salesperson",
    "spokesman": "spokesperson",
    "mothering": "parenting",
    "fathering": "parenting",
    "manmade": "artificial",
    "manpower": "workforce",
    "boyfriend": "partner",
    "girlfriend": "partner",
    "brotherhood": "solidarity",
    "sisterhood": "solidarity",
    "man up": "be strong",
    "woman up": "be strong",
    "lady doctor": "doctor",
    "male nurse": "nurse",
    "working mother": "working parent",
    "career woman": "professional",
    "bossy": "assertive",
    "hysterical": "upset",
    "feisty": "spirited",
    "emotional": "passionate",
    "shrill": "sharp",
    "dramatic": "expressive",
    "aggressive": "assertive",
    "catfight": "argument",
    "boyish": "youthful",
    "girly": "playful",
    "alpha male": "leader",
    "gold digger": "materialistic person",
    "seductress": "charming person",
    "hunk": "attractive person",
    "tomboy": "active child",
    "feminazi": "feminist",
    "bimbo": "person",
    "slut": "promiscuous person",
    "spinster": "single person",
    "diva": "talented individual",
    "whipped": "dedicated partner",
    "nagging wife": "concerned spouse",
    "new mom": "new parent",
    "mompreneur": "entrepreneur",
    "daddy issues": "parental struggles",
    "boy's club": "exclusive group",
    "old boys’ network": "exclusive network",
    "wearing the pants": "taking charge",
    "ball and chain": "partner",
    "chick flick": "romantic movie",
    "ladylike": "polite",
    "like a girl": "graceful",
    "like a man": "strong",
    "run like a girl": "run fast",
    "cry like a girl": "crying is human",
    "mother tongue": "first language",
    "man hours": "work hours",
    "she's asking for it": "consent matters",
    "strong independent woman": "independent person",
    "girlboss": "ambitious person",
    "simp": "devoted person",
    "pick-me girl": "attention-seeker",
    "alpha male": "confident leader",
    "sigma male": "independent person",
    "chad": "confident person",
    "bruh girl": "laid-back person",
    "bimbo": "person",
    "himbo": "kind-hearted person",
    "daddy issues": "parental struggles",
    "mommy issues": "parental struggles",
    "male manipulator": "manipulative person",
    "feminazi": "feminist",
    "slay queen": "successful person",
    "bad b*tch": "strong person",
    "boss babe": "entrepreneur",
    "king behavior": "confident behavior",
    "queen behavior": "confident behavior",
    "that’s so girly": "that’s so stylish",
    "be a man": "be strong",
    "she's a 10 but...": "they are a 10 but...",
    "stay-at-home dad": "stay-at-home parent",
    "stay-at-home mom": "stay-at-home parent",
    "momfluencer": "parent influencer",
    "dad bod": "soft physique",
    "high-maintenance girl": "particular person",
    "nagging wife": "concerned spouse",
    "strong independent woman": "independent person",
    "cry like a girl": "crying is human",
    "throwing like a girl": "throwing poorly",
    "gossiping like women": "spreading rumors",
    "gold digger": "materialistic person",
    "wifey material": "great partner",
    "husband material": "great partner",
    "stay-at-home mom": "stay-at-home parent",
    "bro code": "friendship code",
    "girl dinner": "snack meal",
    "daddy energy": "confident energy",
    "mommy energy": "caring energy",
    "basic white girl": "trendy person",
    "it girl": "trendsetter",
    "soft boy": "sensitive person",
    "man tears": "emotional response",
    "male Karen": "rude person",
    "gatekeep gaslight girlboss": "manipulative behavior",
    "housewife": "homemaker",
    "working woman": "working professional",
    "house husband": "homemaker",
    "boy's school": "all-boys school",
    "girl's school": "all-girls school",
    "lady doctor": "doctor",
    "male nurse": "nurse",
    "career woman": "professional",
    "modern girl": "progressive individual",
    "obedient wife": "supportive spouse",
    "ideal husband": "good partner",
    "man of the house": "head of the household",
    "beta": "child",
    "beti": "child",
    "sanskari daughter-in-law": "respectful daughter-in-law",
    "gharelu girl": "family-oriented person",
    "feminine job": "job",
    "masculine job": "job",
    "homely girl": "family-oriented person",
    "bold woman": "confident individual",
    "macho man": "strong person",
    "ideal wife": "great partner",
    "dominating husband": "controlling spouse",
    "independent girl": "independent person",
    "fragile woman": "sensitive person",
    "girlish hobbies": "creative hobbies",
    "manly hobbies": "adventurous hobbies",
    "overprotective father": "concerned parent",
    "bossy female manager": "assertive manager",
    "daddy's girl": "loved child",
    "mama's boy": "family-loving person",
    "traditional wife": "supportive partner",
    "new-age husband": "progressive spouse",
    "gold digger": "materialistic person",
    "tomboy": "active person",
    "beauty with brains": "intelligent and attractive person",
    "real man": "strong individual",
    "real woman": "strong individual",
    "emotional woman": "expressive person",
    "angry young man": "passionate person",
    "nurturing mother": "caring parent",
    "protective brother": "concerned sibling",
    "male-dominated industry": "traditionally male-led industry",
    "woman-centric movie": "female-led movie",
    "damsel in distress": "person in need of help",
    "breadwinner husband": "primary earner",
    "stay-at-home mom": "stay-at-home parent",
    "stay-at-home dad": "stay-at-home parent",
    "lady-like behavior": "polite behavior",
    "manly behavior": "confident behavior",
    "marriageable girl": "eligible person",
    "high-maintenance woman": "particular person",
    "over-emotional woman": "deeply expressive person",
    "nagging wife": "concerned spouse",
    "strong independent woman": "independent person",
    "cry like a girl": "crying is human",
    "throwing like a girl": "throwing poorly",
    "gossiping like women": "spreading rumors",
    "wifey material": "great partner",
    "husband material": "great partner",
    "old boys network": "exclusive network",
    "wearing the pants": "taking charge",
    "bro code": "friendship code",
    "slut": "bad word"
}


gender_biased_words = [
    "bossy", "emotional", "feisty", "hysterical",
    "irrational", "shrill", "dramatic", "moody",
    "clingy", "flirty", "vain", "whiny", "bitchy",
    "controlling", "needy", "high-maintenance",
    "fragile", "dainty", "domineering", "overly sensitive"
]




